import * as THREE from "three"
import { SVGLoader } from "three/addons/loaders/SVGLoader.js"
import * as BufferGeometryUtils from "three/addons/utils/BufferGeometryUtils.js"

// Marmors: the mark dressed in a Nano Banana texture. The marbled dye
// (generated by Gemini image, saved as nano-texture.png) wraps the extruded
// logotype and does more than paint it: the texture's luminance is read in
// the vertex shader and pushed along the normals, so the gold veins and
// bright ribbons physically emboss the surface, and as the UVs drift the
// relief itself crawls across the letters. Fresnel glass rim, twin
// speculars, the same marble slab drifting dark in the background.

const LOGO_W = 3.2

let width = window.innerWidth || 1280
let height = window.innerHeight || 720

let mouseX = 0, mouseY = 0
let energy = 0
let lastX = null, lastY = null

const canvas = document.getElementById("scene_root")
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true })
// dpr locked to 1 — embedded preview compositors blit canvas bitmaps 1:1
renderer.setPixelRatio(1)

const scene = new THREE.Scene()
scene.background = new THREE.Color(0x000000)
const camera = new THREE.PerspectiveCamera(40, 1, 0.1, 100)

// -- the Nano Banana texture --------------------------------------------------------------

const dyeTex = new THREE.TextureLoader().load("nano-texture.png")
dyeTex.colorSpace = THREE.SRGBColorSpace
dyeTex.wrapS = dyeTex.wrapT = THREE.RepeatWrapping
dyeTex.anisotropy = 4

// -- material: dye paints AND embosses ----------------------------------------------------

const uniforms = {
  uTex: { value: dyeTex },
  uTime: { value: 0 },
  uAmp: { value: 0.045 },
  uRelief: { value: 0.085 },
  uFlow: { value: 1.0 },
  uBBox: { value: new THREE.Vector4(-LOGO_W / 2, -0.42, LOGO_W, 0.84) }
}

function flowGLSL() {
  return /* glsl */ `
    vec2 flowUV(vec2 uv, float t) {
      return uv + 0.08*vec2(sin(uv.y*6.0 + t*2.8), cos(uv.x*5.0 - t*2.3)) + vec2(t*0.09, -t*0.06);
    }
  `
}

const fluidMat = new THREE.ShaderMaterial({
  uniforms,
  vertexShader: /* glsl */ `
    uniform sampler2D uTex;
    uniform float uTime, uAmp, uRelief, uFlow;
    uniform vec4 uBBox;
    varying vec3 vN;
    varying vec3 vPos;
    varying vec3 vView;
    ${flowGLSL()}
    void main() {
      vec3 p = position;
      float t = uTime;
      vec2 uv = (position.xy - uBBox.xy) / uBBox.zw;

      // the marble embosses the surface: bright dye rises, dark sinks
      vec2 fuv = flowUV(uv, t*0.18*uFlow);
      vec3 dye = texture2D(uTex, fuv).rgb;
      float lum = dot(dye, vec3(0.299, 0.587, 0.114));
      float relief = (lum - 0.35) * uRelief;

      // plus the slow jelly breath
      float d = sin(p.x*2.1 + t*1.2) * 0.4
              + sin(p.y*3.4 - t*1.6) * 0.3;
      p += normal * (relief + d * uAmp);

      vec3 n = normal;
      n.x += cos(p.x*2.1 + t*1.2) * uAmp * 3.0;
      n.y += -cos(p.y*3.4 - t*1.6) * uAmp * 3.5;
      vN = normalize(normalMatrix * normalize(n));
      vec4 wp = modelMatrix * vec4(p, 1.0);
      vPos = position;
      vView = normalize(cameraPosition - wp.xyz);
      gl_Position = projectionMatrix * viewMatrix * wp;
    }
  `,
  fragmentShader: /* glsl */ `
    precision highp float;
    uniform sampler2D uTex;
    uniform float uTime, uFlow;
    uniform vec4 uBBox;
    varying vec3 vN;
    varying vec3 vPos;
    varying vec3 vView;
    ${flowGLSL()}
    void main() {
      vec2 uv = (vPos.xy - uBBox.xy) / uBBox.zw;
      float t = uTime * 0.18 * uFlow;

      // two drifts cross-faded — the marble flows without smearing
      vec3 dyeA = texture2D(uTex, flowUV(uv, t)).rgb;
      vec3 dyeB = texture2D(uTex, flowUV(uv * 1.15 + 0.37, -t*0.8)).rgb;
      float k = 0.5 + 0.5*sin(t*4.0);
      vec3 dye = mix(dyeA, dyeB, k);

      vec3 n = normalize(vN);
      vec3 v = normalize(vView);
      if (dot(n, v) < 0.0) n = -n;

      float fres = pow(1.0 - max(dot(n, v), 0.0), 2.6);
      vec3 col = dye * (1.55 + 0.7*max(dot(n, vec3(0.35, 0.55, 0.75)), 0.0));
      col += dye * fres * 2.4;
      col += vec3(1.0, 0.9, 0.7) * fres * 0.30;      // gold-tinged rim

      vec3 l = normalize(vec3(0.5, 0.8, 0.6));
      vec3 h = normalize(l + v);
      col += vec3(1.0, 0.95, 0.85) * pow(max(dot(n, h), 0.0), 70.0) * 1.1;
      vec3 l2 = normalize(vec3(-0.6, -0.2, 0.7));
      col += dye * pow(max(dot(n, normalize(l2 + v)), 0.0), 22.0) * 0.7;

      gl_FragColor = vec4(col, 1.0);
    }
  `
})

// -- build the mark ------------------------------------------------------------------------

let logoGroup = null
new SVGLoader().load("redo-logo.svg", data => {
  const geos = []
  let i = 0
  for (const path of data.paths) {
    for (const shape of SVGLoader.createShapes(path)) {
      const g = new THREE.ExtrudeGeometry(shape, {
        depth: 130, curveSegments: 24, bevelEnabled: false
      })
      g.translate(0, 0, i * 3)
      i++
      geos.push(g)
    }
  }
  let geo = BufferGeometryUtils.mergeGeometries(geos)
  geo = BufferGeometryUtils.mergeVertices(geo, 0.4)
  geo.computeVertexNormals()

  const s = LOGO_W / 1840.49
  geo.scale(s, -s, s)
  geo.computeBoundingBox()
  const bb = geo.boundingBox
  geo.translate(-(bb.min.x + bb.max.x) / 2, -(bb.min.y + bb.max.y) / 2, -(bb.min.z + bb.max.z) / 2)
  geo.computeBoundingBox()
  uniforms.uBBox.value.set(
    geo.boundingBox.min.x, geo.boundingBox.min.y,
    geo.boundingBox.max.x - geo.boundingBox.min.x,
    geo.boundingBox.max.y - geo.boundingBox.min.y
  )

  logoGroup = new THREE.Mesh(geo, fluidMat)
  scene.add(logoGroup)
})

// -- sizing / input ---------------------------------------------------------------------------

function applySize() {
  width = window.innerWidth || width; height = window.innerHeight || height
  renderer.setSize(width, height, false)
  camera.aspect = width / height
  const halfA = Math.atan(Math.tan((camera.fov * Math.PI) / 360) * camera.aspect)
  camera.position.z = (LOGO_W / 2 / 0.78) / Math.tan(halfA)
  camera.updateProjectionMatrix()
}
applySize()
window.addEventListener("resize", applySize)

window.addEventListener("mousemove", e => {
  mouseX = (e.clientX / width - 0.5) * 2
  mouseY = (e.clientY / height - 0.5) * 2
  if (lastX !== null) energy = Math.min(energy + Math.hypot(e.clientX - lastX, e.clientY - lastY) / Math.max(width, height) * 5, 1.6)
  lastX = e.clientX; lastY = e.clientY
})

// -- loop -------------------------------------------------------------------------------------

const clock = new THREE.Clock()
let t = 0

function render() {
  if (width !== window.innerWidth || height !== window.innerHeight) applySize()
  const dt = Math.min(clock.getDelta(), 0.05)
  t += dt
  energy *= Math.pow(0.5, dt)

  uniforms.uTime.value = t
  uniforms.uFlow.value = 1.0 + energy * 2.4
  uniforms.uAmp.value = 0.04 + energy * 0.03

  if (logoGroup) {
    logoGroup.rotation.y = Math.sin(t * 0.35) * 0.26 + mouseX * 0.35
    logoGroup.rotation.x = Math.sin(t * 0.27) * 0.11 - mouseY * 0.22
    logoGroup.rotation.z = Math.sin(t * 0.19) * 0.03
  }

  renderer.render(scene, camera)
}
function animate() { requestAnimationFrame(animate); render() }
animate()

window.__fable = { renderer, scene, camera, get t() { return t }, set t(v) { t = v }, render }
